package com.example.localizacionInalambrica.other

object Constants {

    const val APLICATIONID = "e0ef0e30-b8e6-11eb-8529-0242ac130003"

    const val REQUEST_CODE_LOCATION_PERMISSION = 0

    const val ACTION_START_OR_RESUME_SERVICE_RASTREO = "ACTION_START_OR_RESUME_SERVICE_RASTREO"
    const val ACTION_PAUSE_SERVICE_RASTREO = "ACTION_PAUSE_SERVICE_RASTREO"
    const val ACTION_STOP_SERVICE_RASTREO = "ACTION_STOP_SERVICE_RASTREO"

    const val ACTION_START_SERVICE_BLUETOOTH_RASTREADOR =
        "ACTION_START_OR_RESUME_SERVICE_BLUETOOTH_RASTREADOR"
    const val ACTION_START_SERVICE_BLUETOOTH_CLIENTE =
        "ACTION_START_OR_RESUME_SERVICE_BLUETOOTH_CLIENTE"
    const val ACTION_RESUME_SERVICE_BLUETOOTH = "ACTION_RESUME_SERVICE_BLUETOOTH"
    const val ACTION_PAUSE_SERVICE_BLUETOOTH = "ACTION_PAUSE_SERVICE_BLUETOOTH"
    const val ACTION_STOP_SERVICE_BLUETOOTH = "ACTION_STOP_SERVICE_BLUETOOTH"

    const val ACTION_SHOW_HOME_FRAGMEWNT = "ACTION_SHOW_HOME_FRAGMEWNT"

    const val ACTION_STOP_SERVICE_NOTIFICATION = "ACTION_STOP_SERVICE_NOTIFICATION"
    const val ACTION_RESUME_SERVICE_NOTIFICATION = "ACTION_RESUME_SERVICE_NOTIFICATION"

    const val ACTION_START_OR_RESUME_SERVICE_PARSE = "ACTION_START_OR_RESUME_SERVICE_PARSE"
    const val ACTION_PAUSE_SERVICE_PARSE = "ACTION_PAUSE_SERVICE_PARSE"
    const val ACTION_STOP_SERVICE_PARSE = "ACTION_STOP_SERVICE_PARSE"

    const val NOTIFICATION_CHANEL_ID = "rastreo_channel"
    const val NOTIFICATION_CHANEL_NAME = "Rastreo"
    const val NOTIFICATION_ID = 1

    const val LOCATION_UPDATE_INTERVAL = 5000L
    const val FASTEST_LOCATION_INTERVAL = 2000L

    const val DEFAULT_ZOOM = 18f

    const val BEACON_LAYOUT = "m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"

    const val PREFERENSES_FILE = "mypref"
    const val PREFERENSES_USERNAME = "userName"
    const val PREFERENSES_SERVERADDR = "serveraddr"
    const val PREFERENSES_USERID = "userID"
    const val PREFERENSES_MACKEY32 = "macKey32"
    const val PREFERENSES_CIFRADOKEY88 = "cifradoKey88"
    const val PREFERENSES_USERROLE = "userRole"


}